# Site Settings
# You can change the settings below in order to customize your website.
name: "AutocrossBlog.com"
title: "AutocrossBlog.com"
description: "Documenting autocross, the finest of all motorsports!"
logo: 'assets/GradientLogo.jpg'
favicon: '/assets/favicon.ico'
baseurl: ""
google_analytics: 'G-438M5WVM2K' # configured for Google Analytics 4 MEASUREMENT ID
disqus: autocrossblog-com
mailchimp-list: 
include: ["_pages"]
permalink: /:title/
url: 'https://www.AutocrossBlog.com'

templatemessage: 'Forked from <a  href="https://www.chrishammond.com/">Chris Hammond</a>''s <a href="https://jekyllexample.com">jekyllexample.com</a>.'

# Authors
authors:
  chris:
    name: Chris Hammond
    display_name: Chris Hammond
    gravatar: bff097b7cc348bebce39ee1c7694d125
    email: christoc@christoc.com
    web: https://www.chrishammond.com
    twitter: https://twitter.com/christoc
    description: "Chris Hammond has autocrossed for 24 years, racing in a variety of vehicles from a 1994 VW Golf to a 1999 Z-28, a 2003 350z, a 2004 ZO6 and a 2016 FRS. He is the founder of AutocrossBlog.com and created the ultimate autocross forum, SOLO2.ORG, years ago . Read more at <a href=\"https://www.chrishammond.com\" target=_blank>ChrisHammond.com</a>" 

# Plugins
plugins:
  - jekyll_picture_tag
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-feed
  - jekyll-archives
      
# Archives
jekyll-archives:
  enabled:
    - categories
  layout: archive
  permalinks:
    category: '/category/:name/'
    
# Pagination 
paginate: 9
paginate_path: /page:num/
    
# Other
markdown: kramdown

kramdown:
  input: GFM
  syntax_highlighter: rouge
  syntax_highlighter_opts:
    block:
      line_numbers: true

# Adsense (change to "enabled" to activate, also your client id and ad slot. Create a new ad unit from your Adsense account to get the slot.)
adsense: "disabled"
adsense-data-ad-client: ""
adsense-data-ad-slot: ""

# Lazy Images ("enabled" or "disabled")
lazyimages: "true"

exclude: [changelog.md, LICENSE.txt, README.md, Gemfile, Gemfile.lock]

picture:
  source: "assets/images"
  output: "assets/images_out"
  suppress_warnings: true
  ignore_missing_images: false
  presets:
    default:
      ppi: [1, 1.5]
      source_medium:
        media: "(min-width: 40em)"
        width: "600"
        height: "300"
      source_default:
        width: "300"

defaults:
  - scope:
      path: ""  # An empty string here means all files
      type: "posts"
    values:
      author: "chris"

# exclude:
#  - /assets/images/*